name: Black Formatting Check

# Run on every push and pull request
on: [push, pull_request]

jobs:
  call-format-check:
    uses: project-carpi/.github/.github/workflows/black-check.yml@main
    permissions:
      contents: read
    secrets: inherit
